spring:
  profiles:
    active:
      - local-env
    group:
      local-env:
        - local
      dev-env:
        - dev
      prod-env:
        - prod
    include:
      - jwt
      - slack

server:
  port: 8085